### ISSUE TITLE
System Font Stacks

### ISSUE THREAD

**Issue by Mischback** [Mischback/mischback.de#137]
Font selection was a [real issue](https://github.com/Mischback/mischback.de/issues/30) while coming up with a design, and finally three major fonts were selected and are - as of now - provided as web fonts.

Everything is working fine, but...

- fonts add around 250kb to the website's *weight*
- they add build complexity (if/when further optimisation is applied, see #34)
- external dependencies mean possible licensing issues (this *should* have been covered during selection already, but license terms might change and have to be watched; see #30)
- Flash of invisible Text (FOIT) / Flash of unstyled Text (FOUT) *will* happen!

As an **alternative**, *system font stacks* may be used. The major drawback is loosing some control of the actual design, as the available fonts may deviate heavily between different users/devices.

## ToDo

- [x] select visually fitting font-stacks
  - [x] great starting point: https://github.com/system-fonts/modern-font-stacks
    - [x] [Neo Grotesque](https://github.com/system-fonts/modern-font-stacks?tab=readme-ov-file#neo-grotesque) for ``Mona Lisa``
      - [x] checked on Windows / Edge:
        - basically a *drop in* replacement, no adjustments required! 
      - [x] checked on Windows / Chrome
      - [x] checked on Ubuntu / Firefox
        - *aside box titles* are not vertically centered!
      - [x] checked on Ubuntu / Chromium
      - [x] checked on Android / Chrome
    - [x] [Transitional](https://github.com/system-fonts/modern-font-stacks?tab=readme-ov-file#transitional) for ``Crimson Pro``
      - [x] checked on Windows / Edge
      - [x] checked on Windows / Chrome
      - [x] checked on Ubuntu / Firefox
        - basically nice replacement, *tubhrq* might need a smaller font size
        - *admonition titles* are good
        - *tubhrq* decoration is good! 
      - [x] checked on Ubuntu / Chromium
      - [x] checked on Android / Chrome
        - *tubhrq* might need s smaller font size
